# Generated by Django 4.1.7 on 2023-02-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdoptionForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dog_id", models.IntegerField()),
                ("application_status", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("species", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=20)),
                ("intake_date", models.DateTimeField(auto_now_add=True)),
                ("fertile", models.BooleanField()),
                ("picture", models.URLField(null=True)),
                ("status", models.CharField(max_length=200)),
            ],
        ),
    ]
